function foldQuery(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{M}/gu, "");
}

/** Occupation words in the search box — not cities. Keep in sync with search_terms.py. */
const JOB_QUERY_ALIASES = new Set([
  "fleuriste",
  "fleuristes",
  "florist",
  "florists",
  "floristin",
  "florista",
  "fiorista",
  "floristeria",
  "floristerie",
  "blumenfach",
  "cajero",
  "cajera",
  "cajeros",
  "cashier",
  "caissier",
  "caissiere",
  "kassierer",
  "kassierin",
  "caixa",
  "infirmier",
  "infirmiere",
  "infirmiers",
  "infirmieres",
  "nurse",
  "nursing",
  "enfermero",
  "enfermera",
  "enfermeiro",
  "enfermeira",
  "krankenpfleger",
  "krankenschwester",
  "pflege",
  "soignant",
  "soignante",
  "developpeur",
  "developpeuse",
  "developpeurs",
  "developer",
  "developers",
  "desarrollador",
  "programador",
  "programmeur",
  "software",
  "informatique",
  "informatico",
  "chauffeur",
  "chauffeurs",
  "chauffeuse",
  "conducteur",
  "conductora",
  "conductor",
  "fahrer",
  "fahrerin",
  "driver",
  "chofer",
  "comptable",
  "comptables",
  "accountant",
  "accounting",
  "contable",
  "contabilista",
  "buchhalter",
  "buchhalterin",
  "comptabilite",
  "cuisinier",
  "cuisiniere",
  "cuisiniers",
  "cocinero",
  "cocinera",
  "cozinheiro",
  "cozinheira",
  "koch",
  "kochin",
  "chef",
  "cuisine",
  "enseignant",
  "enseignante",
  "enseignants",
  "professeur",
  "professeure",
  "profesor",
  "profesora",
  "professor",
  "professora",
  "teacher",
  "lehrperson",
  "docent",
  "vendeur",
  "vendeuse",
  "vendeurs",
  "vendedor",
  "vendedora",
  "verkaufer",
  "verkaeufer",
  "verkauferin",
  "verkaeuferin",
  "retail",
  "vente",
]);

/** True when the search box is an occupation word, not a city. */
export function queryLooksLikeJob(query: string): boolean {
  const folded = foldQuery(query);
  if (!folded) return false;
  if (JOB_QUERY_ALIASES.has(folded)) return true;
  return folded.split(/\s+/).some((token) => JOB_QUERY_ALIASES.has(token));
}
